services:
  backend-blue:
    image: ghcr.io/prafalex/car-inventory-devops/backend:${BUILD_TAG}
    container_name: car_backend_blue
    env_file:
      - .env.blue
    ports:
      - "8002:8000"
    networks:
      - car-production-network

  frontend-blue:
    image: ghcr.io/prafalex/car-inventory-devops/frontend:${BUILD_TAG}
    container_name: car_frontend_blue
    environment:
      - BACKEND_HOST=backend-blue
      - BACKEND_PORT=8000
    ports:
      - "3002:80"
    depends_on:
      - backend-blue
    networks:
      - car-production-network

networks:
  car-production-network:
    external: true