services:
  backend-green:
    image: ghcr.io/prafalex/car-inventory-devops/backend:${BUILD_TAG}
    container_name: car_backend_green
    env_file:
      - .env.green
    ports:
      - "8003:8000"
    networks:
      - car-production-network

  frontend-green:
    image: ghcr.io/prafalex/car-inventory-devops/frontend:${BUILD_TAG}
    container_name: car_frontend_green
    environment:
      - BACKEND_HOST=backend-green
      - BACKEND_PORT=8000
    ports:
      - "3003:80"
    depends_on:
      - backend-green
    networks:
      - car-production-network

networks:
  car-production-network:
    external: true