upstream live_backend {
    server localhost:8002;
}

upstream live_frontend {
    server localhost:3002;
}

server {
    listen 80;

    location /api/ {
        proxy_pass http://live_backend/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://live_frontend/;
        proxy_set_header Host $host;
    }
}